
- name: Provision Web Servers
  hosts: tag_group_web
  become: true
  tasks:
    - name: Install pip3
      apt:
        update_cache: yes
        name: python3-pip
    

    - name: Install python docker sdk
      shell: |
        pip3 install docker
    
    - name: Install docker
      apt:
        name: docker.io
     

    - name: Start Docker
      shell: |
        systemctl start docker
        systemctl enable docker
   

    - name: Run Image
      shell: docker run --name hello -dit -p 80:80 -p 443:443 imhl/nginx-static
   